mysql:
  build: ./mysql
  environment:
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpassword
    - MYSQL_ROOT_PASSWORD=dbrootpassword
    - MYSQL_DATABASE=dbdatabase
  volumes:
    - db:/var/lib/mysql
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql
  environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
  ports:
    - '8088:80'
phpapache:
  build: ./apache
  ports:
    - '8080:80'
  volumes:
    - ./html:/var/www/html
  links:
    - mysql
  volumes:
    - db:/var/lib/mysql
